services:
  - type: web
    name: medubs-backend
    env: python
    region: oregon
    plan: free
    # Instala dependências
    buildCommand: cd backend && pip install -r requirements.txt
    # Usa Uvicorn direto (Melhor prática para Produção)
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
