name: medubs
description: IA Clínica Inteligente para profissionais de saúde.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Logic
  google_generative_ai: ^0.4.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.0
  http: ^1.2.0
  intl: ^0.19.0
  diacritic: ^0.1.5

  # Audio
  record: ^4.4.4
  audioplayers: ^6.0.0
  permission_handler: ^11.3.0
  
  # UI
  cupertino_icons: ^1.0.6
  
  # PDF
  pdf: ^3.10.0
  printing: ^5.11.0 # Useful for printing/sharing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon.png
    - assets/splash.png
    - assets/db_remume.json
    - assets/db_rename.json
    - assets/db_alto_custo.json
